name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4

  install-dependencies:
    runs-on: ubuntu-latest
    needs: install-poetry
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: poetry run task lint

  format:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run code formatter
        run: poetry run task formatter

  security:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run security check
        run: poetry run task security
