name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4
      - name: Install dependencies
        run: poetry install --no-root

  static-code-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run linter (flake8)
        run: |
          # Dodaj tutaj polecenia do uruchomienia flake8
      - name: Run code formatter
        run: |
          # Dodaj tutaj polecenia do uruchomienia narzędzia formatującego kod
      - name: Run security check
        run: |
          # Dodaj tutaj polecenia do sprawdzenia zabezpieczeń

  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run unit tests
        run: |
          poetry run pytest
