name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH=$HOME/.local/bin:$PATH  # Make sure Poetry is in the PATH

  install-dependencies:
    runs-on: ubuntu-latest
    needs: install-poetry
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install project dependencies
        run: |
          ~/.local/bin/poetry install --no-root

  unit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          ~/.local/bin/poetry run task test

  static-code-analysis:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: |
          ~/.local/bin/poetry run task lint

  formatting:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run code formatter
        run: |
          ~/.local/bin/poetry run task formatter

  security:
    runs-on: ubuntu-latest
    needs: install-dependencies
    strategy:
      matrix:
        cache-key: [security-cache]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run security check
        run: |
          ~/.local/bin/poetry run task security

  cache-venv:
    runs-on: ubuntu-latest
    needs: [install-poetry, install-dependencies, unit-tests, static-code-analysis, formatting, security]
    steps:
      - name: Cache build venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ runner.os }}-venv
