name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry Action
        uses: snok/install-poetry@v1.3.4

  install-dependencies:
    runs-on: ubuntu-latest
    needs: install-poetry
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: poetry run task lint

  formatting:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run code formatter
        run: poetry run task formatter

  security:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    strategy:
      matrix:
        cache-key: [security-cache]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ matrix.cache-key }}
      - name: Run security check
        run: poetry run task security
      - name: Save cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ matrix.cache-key }}
