name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH=$HOME/.local/bin:$PATH  # Make sure Poetry is in the PATH

  install-dependencies:
    runs-on: ubuntu-latest
    needs: install-poetry
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create directory if not exists
        run: mkdir -p ./example-app  # Tworzy katalog, jeśli go nie ma
      - name: Move to the directory
        run: cd ./example-app         # Przechodzi do katalogu
      - name: Install project dependencies
        run: |
          poetry install --no-root

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: |
          source $HOME/.poetry/env
          poetry run task lint

  formatting:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run code formatter
        run: |
          source $HOME/.poetry/env
          poetry run task formatter

  security:
    runs-on: ubuntu-latest
    needs: install-dependencies
    defaults:
      run:
        working-directory: ./example-app
    strategy:
      matrix:
        cache-key: [security-cache]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ matrix.cache-key }}
      - name: Run security check
        run: |
          source $HOME/.poetry/env
          poetry run task security
      - name: Save cache
        uses: actions/cache@v2
        with:
          path: /home/runner/work/<path>/example-app/.venv
          key: ${{ matrix.cache-key }}
