name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

  install-dependencies:
    runs-on: ubuntu-latest
    needs: install-poetry
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install project dependencies
        run: |
          cd ./example-app  # Przechodzi do katalogu aplikacji
          $HOME/.poetry/bin/poetry install --no-root

  unit-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: |
          cd ./example-app  # Przechodzi do katalogu aplikacji
          $HOME/.poetry/bin/poetry run task test

  static-code-analysis:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: |
          cd ./example-app  # Przechodzi do katalogu aplikacji
          $HOME/.poetry/bin/poetry run task lint
